/* Automatically generated by './build/bin/build-entry.js' */

import Breadcrumb from '../packages/Breadcrumb/index.js';
import GroupButton from '../packages/Button/index.js';
import GroupCheckbox from '../packages/Checkbox/index.js';
import GroupDatePicker from '../packages/DatePicker/index.js';
import Hamburger from '../packages/Hamburger/index.js';
import NumberInput from '../packages/Input/NumberInput.js';
import StringInput from '../packages/Input/StringInput.js';
import TextareaInput from '../packages/Input/TextareaInput.js';
import ModalDialog from '../packages/Modal/ModalDialog.js';
import ModalForm from '../packages/Modal/ModalForm.js';
import ModalTable from '../packages/Modal/ModalTable.js';
import GroupRadio from '../packages/Radio/index.js';
import GroupSelect from '../packages/Select/index.js';
import ComplexTable from '../packages/Table/ComplexTable.js';
import TableCheckBox from '../packages/Table/TableCheckBox.js';
import TableText from '../packages/Table/TableText.js';

const components = [
    Breadcrumb,
    GroupButton,
    GroupCheckbox,
    GroupDatePicker,
    Hamburger,
    NumberInput,
    StringInput,
    TextareaInput,
    ModalDialog,
    ModalForm,
    ModalTable,
    GroupRadio,
    TableText,
    GroupSelect,
    ComplexTable,
    TableCheckBox
];

const install = function(Vue, opts = {}) {
    components.forEach(component => {
        Vue.component(component.name, component);
    });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
}

export default {
    version: '0.1.0',
    install,
    Breadcrumb,
    GroupButton,
    GroupCheckbox,
    GroupDatePicker,
    Hamburger,
    NumberInput,
    StringInput,
    TextareaInput,
    ModalDialog,
    ModalForm,
    ModalTable,
    GroupRadio,
    TableText,
    GroupSelect,
    ComplexTable,
    TableCheckBox
  
};